export { CompilerPipeline } from './compilerPipeline.ts';
export type { PipelineCompilationReport } from './compilerPipeline.ts';
export { DocumentNormalizer } from './documentNormalizer.ts';
export type { NormalizationResult, NormalizationStats } from './documentNormalizer.ts';
export { DocumentReconstructor } from './documentReconstructor.ts';
export type { ReconstructionResult, ReconstructionSummary } from './documentReconstructor.ts';
export { LogicalBlockBuilder } from './logicalBlockBuilder.ts';
export { OCR_NOISE_REPLACEMENTS, normalizeOcrText } from './ocrNoiseDictionary.ts';
export type { OcrReplacementRule } from './ocrNoiseDictionary.ts';
export { OmlGenerator } from './omlGenerator.ts';
export { QuestionGraphBuilder } from './questionGraphBuilder.ts';
export { SemanticAnalyzer } from './semanticAnalyzer.ts';
export { Tokenizer } from './tokenizer.ts';
export { Validator } from './validator.ts';
export type { ValidationDiagnostics, ValidationResult, ValidationStatus } from './validator.ts';
export type { LogicalBlock, LogicalBlockKind, LogicalOption } from './logicalBlockBuilder.ts';
export type { SemanticBlock, SemanticRole } from './semanticAnalyzer.ts';
export type { DocumentGraph, GraphNode, GraphQuestion, GraphReadingPassage } from './questionGraphBuilder.ts';
export type { Token, TokenKind, TokenMeta } from './tokens.ts';
